# permissions for end users to view skedlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skedler-viewer-role
rules:
- apiGroups:
  - skedler.skedler.com
  resources:
  - skedlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skedler.skedler.com
  resources:
  - skedlers/status
  verbs:
  - get
