# permissions for end users to edit skedlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skedler-editor-role
rules:
- apiGroups:
  - skedler.skedler.com
  resources:
  - skedlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skedler.skedler.com
  resources:
  - skedlers/status
  verbs:
  - get
